### ISSUE TITLE
2. 添加一个team页面

### ISSUE THREAD

**Issue by windy** [railsgirls-cn/railsgirlschina#4]
可考虑按照姓氏的首字母排名。 然后有Tab，按地区来分.

先讨论

**Comment by sundevilyang** [comment]
这个可以有  组织者还是很辛苦的，让大家认识一下很应该

**Comment by sundevilyang** [comment]
1. 超级管理员可以在后台添加team成员
2. 这个页面分两部分：第一部分是 organizer，第二部分是 tutors。  头像+简介（都是使用个人 profile 的数据，点击头像跳转到个人的 profile）
